'use client'

import { motion } from 'framer-motion'
import { usePeopleDex } from '@/lib/peopledex-context'
import { levelFromXp } from '@/lib/game-engine'
import Link from 'next/link'
import { ArrowUpRight, Camera, ChevronRight, Grid3X3, ScanLine, ScrollText, Sparkles, Trophy, Users, Zap } from 'lucide-react'
import OrbitField from '@/components/OrbitField'

export default function HomePage() {
  const { profile, people, quests, achievements } = usePeopleDex()
  if (!profile) return null
  const lvl = levelFromXp(profile.xp)
  const pct = (lvl.currentXp / lvl.nextLevelXp) * 100
  const today = new Date().toISOString().slice(0, 10)
  const todayCount = people.filter(p => p.capturedAt.startsWith(today)).length
  const unclaimed = quests.filter(q => q.completed && !q.claimed).length
  const completedAch = achievements.filter(a => a.completed).length
  const recent = [...people].sort((a, b) => new Date(b.capturedAt).getTime() - new Date(a.capturedAt).getTime()).slice(0, 3)

  return <div className="screen-shell">
    <header className="mb-8 grid gap-7 lg:grid-cols-[1.1fr_.9fr] lg:items-end">
      <div><p className="eyebrow mb-5">PeopleDex / personal field guide / 001</p><h1 className="screen-title">The people<br /><em>around you.</em></h1><p className="mt-6 max-w-md text-sm leading-6 text-[#92988a]">A living archive of small encounters. Point, notice, remember — then leave the rest to your own private collection.</p><div className="mt-7 flex items-center gap-3"><Link href="/camera" className="group flex items-center gap-3 rounded-full bg-[#d8f36a] px-5 py-3 text-sm font-extrabold text-[#111310] transition-transform hover:-translate-y-1"><Camera className="h-4 w-4" /> Start a sighting <ArrowUpRight className="h-4 w-4 transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></Link><Link href="/collection" className="mono flex items-center gap-2 px-2 text-[10px] uppercase tracking-[.12em] text-[#92988a] hover:text-[#f4f1e8]">Open archive <ChevronRight className="h-3 w-3" /></Link></div></div>
      <div className="relative lg:pl-8"><div className="absolute -left-2 bottom-6 top-6 hidden w-px bg-gradient-to-b from-transparent via-[#d8f36a]/50 to-transparent lg:block" /><OrbitField count={people.length} /></div>
    </header>

    <div className="signal-line mb-7" />
    <section className="grid gap-3 lg:grid-cols-[1.15fr_.85fr]">
      <div className="grid grid-cols-3 gap-3">{[{ icon: Users, value: profile.totalCaptures, label: 'total sightings', bg: 'bg-[#d8f36a]/10', text: 'text-[#d8f36a]' }, { icon: Grid3X3, value: people.length, label: 'unique entries', bg: 'bg-[#8fc7ff]/10', text: 'text-[#8fc7ff]' }, { icon: ScanLine, value: todayCount, label: 'today', bg: 'bg-[#f19a62]/10', text: 'text-[#f19a62]' }].map(({ icon: Icon, value, label, bg, text }) => <div key={label} className="glass relative overflow-hidden p-5"><div className={`mb-8 flex h-8 w-8 items-center justify-center rounded-lg ${bg}`}><Icon className={`h-4 w-4 ${text}`} /></div><div className="text-3xl font-bold tracking-[-.08em] text-[#f4f1e8]">{value}</div><div className="mono mt-2 text-[9px] uppercase tracking-[.12em] text-[#92988a]">{label}</div></div>)}</div>
      <div className="glass flex items-center gap-5 p-5"><div className="relative flex h-20 w-20 shrink-0 items-center justify-center rounded-full border border-[#d8f36a]/40 bg-[#d8f36a]/10"><span className="text-3xl font-bold tracking-[-.1em] text-[#f4f1e8]">{profile.level}</span><span className="absolute -bottom-1 rounded-full bg-[#d8f36a] px-2 py-0.5 text-[8px] font-black uppercase text-[#111310]">level</span></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between"><span className="eyebrow !text-[#92988a]">Progression</span><Zap className="h-4 w-4 text-[#f19a62]" /></div><div className="mt-3 flex justify-between mono text-[10px] text-[#92988a]"><span>{lvl.currentXp.toLocaleString()} XP</span><span>{lvl.nextLevelXp.toLocaleString()} XP</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/[.08]"><motion.div className="h-full rounded-full bg-gradient-to-r from-[#d8f36a] to-[#f19a62]" initial={{ width: 0 }} animate={{ width: `${pct}%` }} transition={{ duration: 1 }} /></div>{profile.currentStreak > 0 && <p className="mt-3 text-xs font-bold text-[#f19a62]">🔥 {profile.currentStreak} days in the field</p>}</div></div>
    </section>

    {unclaimed > 0 && <Link href="/quests" className="group mt-4 flex items-center gap-4 rounded-2xl border border-[#f19a62]/35 bg-[#2a211b] p-4 transition-colors hover:bg-[#35271e]"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#f19a62]/15"><ScrollText className="h-5 w-5 text-[#f19a62]" /></div><div className="flex-1"><div className="text-sm font-bold text-[#f4f1e8]">A few notes are waiting in the margin</div><div className="mono mt-1 text-[10px] uppercase tracking-wider text-[#f19a62]">{unclaimed} reward{unclaimed === 1 ? '' : 's'} ready to claim</div></div><ArrowUpRight className="h-4 w-4 text-[#f19a62] transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></Link>}

    <section className="mt-12"><div className="mb-5 flex items-end justify-between"><div><p className="eyebrow !text-[#92988a]">Recent signal</p><h2 className="mt-2 text-2xl font-bold tracking-[-.06em] text-[#f4f1e8]">Latest encounters</h2></div><Link href="/collection" className="mono flex items-center gap-1 text-[10px] uppercase tracking-wider text-[#d8f36a]">See all <ArrowUpRight className="h-3 w-3" /></Link></div>{recent.length ? <div className="grid gap-3 sm:grid-cols-3">{recent.map((p, i) => <Link key={p.id} href="/collection" className="group relative min-h-[270px] overflow-hidden rounded-2xl border border-white/10 bg-[#1a1d18]"><img src={p.thumbnailData} alt={p.nickname} className="absolute inset-0 h-full w-full object-cover opacity-80 grayscale-[.15] transition duration-700 group-hover:scale-105 group-hover:opacity-100 group-hover:grayscale-0" /><div className="absolute inset-0 bg-gradient-to-t from-[#111310] via-[#111310]/35 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-4"><div className="flex items-end justify-between"><div><div className="mono text-[9px] tracking-[.16em] text-[#d8f36a]">ENTRY 0{i + 1} / {p.rarity}</div><p className="mt-1 text-lg font-bold tracking-[-.04em] text-[#f4f1e8]">{p.nickname}</p></div><ArrowUpRight className="h-4 w-4 text-[#d8f36a] transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></div></div></Link>)}</div> : <Link href="/camera" className="glass flex min-h-[190px] items-center justify-center gap-3 text-sm text-[#92988a] hover:text-[#f4f1e8]"><Sparkles className="h-4 w-4 text-[#d8f36a]" /> Your archive is waiting for its first story</Link>}</section>

    <section className="mt-12 grid gap-3 pb-4 sm:grid-cols-2"><Link href="/achievements" className="glass glass-hover group flex items-center gap-4 p-5"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#f19a62]/10"><Trophy className="h-5 w-5 text-[#f19a62]" /></div><div className="flex-1"><p className="text-sm font-bold text-[#f4f1e8]">Milestones</p><p className="mono mt-1 text-[10px] uppercase tracking-wider text-[#92988a]">{completedAch}/{achievements.length} unlocked</p></div><ArrowUpRight className="h-4 w-4 text-[#92988a] transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></Link><Link href="/stats" className="glass glass-hover group flex items-center gap-4 p-5"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#8fc7ff]/10"><Grid3X3 className="h-5 w-5 text-[#8fc7ff]" /></div><div className="flex-1"><p className="text-sm font-bold text-[#f4f1e8]">Pattern library</p><p className="mono mt-1 text-[10px] uppercase tracking-wider text-[#92988a]">Read the shape of your collection</p></div><ArrowUpRight className="h-4 w-4 text-[#92988a] transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></Link></section>
  </div>
}
