'use client'

import { motion } from 'framer-motion'
import type { PersonEntry } from '@/lib/types'
import { usePeopleDex } from '@/lib/peopledex-context'
import { ArrowUpRight, Calendar, Hash, MapPin, Star, Trash2, X, Zap } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

const R_LABELS: Record<string, { label: string; color: string }> = { common: { label: 'Common', color: '#aeb5a4' }, uncommon: { label: 'Uncommon', color: '#d8f36a' }, rare: { label: 'Rare', color: '#8fc7ff' }, epic: { label: 'Epic', color: '#dca5ff' }, legendary: { label: 'Legendary', color: '#f19a62' }, mythic: { label: 'Mythic', color: '#ff8bbd' }, ultrarare: { label: 'Ultra Rare', color: '#79e2d4' }, secret: { label: 'Secret', color: '#ffe08a' } }

export default function PersonDetail({ person, onClose }: { person: PersonEntry; onClose: () => void }) {
  const { deletePerson, toggleFavorite } = usePeopleDex(); const r = R_LABELS[person.rarity] || R_LABELS.common
  const details: Array<[LucideIcon, string, string]> = [[Calendar, 'Captured', new Date(person.capturedAt).toLocaleDateString()], [Hash, 'Encounters', String(person.encounterCount)], [Zap, 'XP earned', `${person.xp} XP`]]
  if (person.location) details.push([MapPin, 'Coordinates', `${person.location.latitude.toFixed(2)}, ${person.location.longitude.toFixed(2)}`])
  return <motion.div className="fixed inset-0 z-50 flex items-center justify-center p-4" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose}><div className="absolute inset-0 bg-[#050604]/80 backdrop-blur-xl" /><motion.div className="relative grid w-full max-w-3xl overflow-hidden rounded-[1.7rem] border border-white/15 bg-[#171b15] shadow-2xl md:grid-cols-[1.05fr_.95fr]" initial={{ scale: .94, y: 20 }} animate={{ scale: 1, y: 0 }} exit={{ scale: .94, y: 20 }} transition={{ type: 'spring', damping: 25, stiffness: 300 }} onClick={e => e.stopPropagation()}>
    <button onClick={onClose} aria-label="Close" className="absolute right-4 top-4 z-10 rounded-full border border-white/15 bg-[#111310]/70 p-2 text-[#aeb5a4] hover:text-[#f4f1e8]"><X className="h-4 w-4" /></button>
    <div className="relative min-h-[360px] bg-[#242921]"><img src={person.imageData} alt={person.nickname} className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#111310] via-transparent to-[#111310]/20" /><div className="absolute bottom-5 left-5"><div className="eyebrow" style={{ color: r.color }}>{r.label} sighting</div><h2 className="mt-2 text-4xl font-bold tracking-[-.08em] text-[#f4f1e8]">{person.nickname}</h2></div><button onClick={() => toggleFavorite(person.id)} aria-label="Toggle favorite" className="absolute bottom-5 right-5 rounded-full border border-white/15 bg-[#111310]/70 p-3 backdrop-blur"><Star className={`h-5 w-5 ${person.favorite ? 'fill-[#f19a62] text-[#f19a62]' : 'text-[#f4f1e8]'}`} /></button></div>
    <div className="flex flex-col p-6 md:p-8"><div className="mono text-[10px] uppercase tracking-[.18em] text-[#92988a]">Archive record / #{person.id.slice(-8)}</div><p className="mt-4 text-sm leading-6 text-[#aeb5a4]">A small moment, held still. This entry has crossed your path {person.encounterCount} time{person.encounterCount === 1 ? '' : 's'}.</p><div className="mt-8 grid grid-cols-2 gap-2">{details.map(([Icon, label, value]) => <div key={label} className="rounded-xl border border-white/10 bg-white/[.03] p-3"><div className="flex items-center gap-1.5 text-[10px] uppercase tracking-wider text-[#92988a]"><Icon className="h-3 w-3" />{label}</div><div className="mt-2 truncate text-sm font-semibold text-[#f4f1e8]" style={label === 'XP earned' ? { color: r.color } : undefined}>{value}</div></div>)}</div>{person.tags.length > 0 && <div className="mt-6 flex flex-wrap gap-2">{person.tags.map(tag => <span key={tag} className="rounded-full border border-white/10 px-3 py-1.5 mono text-[10px] text-[#aeb5a4]">{tag}</span>)}</div>}<div className="mt-auto flex gap-2 pt-8"><button onClick={() => { deletePerson(person.id); onClose() }} className="flex flex-1 items-center justify-center gap-2 rounded-xl border border-[#ef806b]/30 py-3 text-xs font-bold text-[#ef806b] hover:bg-[#ef806b]/10"><Trash2 className="h-4 w-4" /> Remove record</button><button onClick={onClose} className="flex items-center justify-center rounded-xl bg-[#d8f36a] px-4 text-[#111310]"><ArrowUpRight className="h-4 w-4" /></button></div></div>
  </motion.div></motion.div>
}
